services:
  # Servidor
  server:
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=server
      - PORT=9000
      - NODO1=node1:8000
      - NODO2=node2:8001
      - NODO3=node3:8002
      - NODO4=node4:8003
      - NODO5=node5:8004
      - NODO6=node6:8005
      - NODO7=node7:8006
      - NODO8=node8:8007
      - NODO9=node9:8008
    ports:
      - "9000:9000"
    networks:
      - nodes_network
      - app
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9

  # NODOS CLIENTES
  node1:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node1
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - nodes_network

  node2:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node2
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - nodes_network

  node3:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node3
      - PORT=8002
    ports:
      - "8002:8002"
    networks:
      - nodes_network

  node4:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node4
      - PORT=8003
    ports:
      - "8003:8003"
    networks:
      - nodes_network

  node5:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node5
      - PORT=8004
    ports:
      - "8004:8004"
    networks:
      - nodes_network

  node6:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node6
      - PORT=8005
    ports:
      - "8005:8005"
    networks:
      - nodes_network

  node7:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node7
      - PORT=8006
    ports:
      - "8006:8006"
    networks:
      - nodes_network

  node8:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node8
      - PORT=8007
    ports:
      - "8007:8007"
    networks:
      - nodes_network

  node9:
    build:
      context: ./backend/client
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=node9
      - PORT=8008
    ports:
      - "8008:8008"
    networks:
      - nodes_network

  # API ENDPOINT (BACKEND)
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      - PORT=9015
    ports:
      - "9015:9015"
    networks:
      - app
    depends_on:
      - server

  # Angular frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app
    depends_on:
      - server
  
networks:
  nodes_network:
  app:
